# Generated by Django 2.0.4 on 2018-04-29 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(max_length=150, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True, verbose_name='ZIP'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='Rating'),
        ),
    ]
