# Generated by Django 2.0.4 on 2018-04-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180429_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='feed.Review', verbose_name='review'),
        ),
    ]
