# Generated by Django 2.0.4 on 2018-04-29 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180429_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
