# Generated by Django 2.0.4 on 2018-04-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_auto_20180429_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='feed.Review', verbose_name='review'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('restaurant', 'user')},
        ),
    ]
