name: app
dependencies:
  - python=3.6
  - pip:
    - django==2.0.4
    - djangorestframework==3.7.7
    - djangorestframework-simplejwt==3.2.3
    - coreapi==2.3.3
    - flake8==3.5.0
    - django-cors-headers==2.2.0
