# Generated by Django 2.0.4 on 2018-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('$', '$'), ('low', '$'), ('medium', '$$'), ('high', '$$$')], default='$', max_length=100, verbose_name='status'),
        ),
    ]
