# Generated by Django 2.0.4 on 2018-05-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180430_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentupdatehistory',
            name='comment',
        ),
        migrations.DeleteModel(
            name='CommentUpdateHistory',
        ),
    ]
