# Generated by Django 2.0.4 on 2018-05-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180501_0914'),
        ('restaurant', '0002_auto_20180430_1556'),
    ]

    operations = [
    ]
