# Generated by Django 2.0.4 on 2018-05-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180501_0831'),
        ('restaurant', '0004_merge_20180501_1118'),
    ]

    operations = [
    ]
